name: auth
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.3
  dio: ^5.1.1 # http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0
  formz: ^0.6.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  injectable: ^2.1.2
  intl: ^0.17.0
  go_router: ^6.5.7
  logger: ^1.1.0

  # Use for responsive UI, set default size base on Mock Up
  flutter_screenutil: ^5.7.0

  # Firebase
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.4

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

  mockito: ^5.4.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  bloc_test: ^9.1.4
  http_mock_adapter: ^0.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
